name: 'Point Roulette Issue 생성'
description: 'Point Roulette Issue를 생성합니다. '
labels: [ order ]
title: 'Issue Title을 작성하세요'
body:
  - type: input
    id: description
    attributes:
      label: 'Issue 내용(Description)'
      description: 'Issue에 대해서 간략히 설명해주세요'
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: '상세 내용(Details)'
      description: 'Issue에 대해서 자세히 설명해주세요'
      value: |
        -
    validations:
      required: true

